# Generated by Django 2.2 on 2019-12-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191223_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_to',
        ),
    ]
