# Generated by Django 2.2 on 2019-12-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191223_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=models.CharField(default='Tags', max_length=255),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
