# Generated by Django 2.2 on 2019-12-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191223_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Article'),
        ),
    ]
