# Generated by Django 2.2 on 2019-12-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191223_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(default='category', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='Video', max_length=200)),
                ('desctiption_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='similar',
            name='similar',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='number_of',
        ),
        migrations.AddField(
            model_name='author',
            name='author_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='myapp.Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='myapp.Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_likes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Like'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to='myapp.Video'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author_of',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='myapp.Author'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Similar',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='category',
            name='video_cat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Video'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='ad_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertise_to_video', to='myapp.Video'),
        ),
        migrations.AddField(
            model_name='author',
            name='author_videos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='myapp.Video'),
        ),
        migrations.AddField(
            model_name='like',
            name='like_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_like', to='myapp.Video'),
        ),
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Video'),
        ),
    ]
