# Generated by Django 2.2 on 2019-12-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191225_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_videos',
        ),
        migrations.AddField(
            model_name='video',
            name='video_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to='myapp.Author'),
        ),
    ]
