# Generated by Django 2.2 on 2019-12-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_comments',
        ),
    ]
