# Generated by Django 2.2 on 2019-12-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_comment_author_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='video_cat',
        ),
        migrations.AddField(
            model_name='video',
            name='video_cat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Category'),
        ),
    ]
